name: Run CountUp Bot
on:
  schedule:
    - cron: '27 18 * * *' # 11:57 PM IST (6:27 PM UTC)
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10.2'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tweepy
    - name: Run the bot
      run: |
        python app.py
      env:
        TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
        TWITTER_API_SECRET_KEY: ${{ secrets.TWITTER_API_SECRET_KEY }}
        TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
    - name: Commit logs
      if: always()
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add logs.txt stop.txt || true
        git commit -m 'Update logs and stop flag' || true
        git push || true
